name: DevTest
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Install Pytest
      run: pip3 install pytest setuptools --upgrade
    - name: Install DeepStack Client SDK
      run: python3 setup.py install --user
    - name: Test Scene
      run: |
        sudo docker run -d --name deepstack -e VISION-SCENE=True -p 80:5000 deepquestai/deepstack:cpu-2020.12
        cd tests
        export TEST_IMAGES_DIR=$PWD"/images"
        export TEST_DEEPSTACK_URL="http://localhost:80"
        cd scene
        python3 -m pytest
        sudo docker container rm -f deepstack
    - name: Test Detection
      run: |
        sudo docker run -d --name deepstack -e VISION-DETECTION=True -p 80:5000 deepquestai/deepstack:cpu-2020.12
        cd tests
        export TEST_IMAGES_DIR=$PWD"/images"
        export TEST_DEEPSTACK_URL="http://localhost:80"
        cd detection
        python3 -m pytest
        sudo docker container rm -f deepstack

    - name: Test Face
        run: |
          sudo docker run -d --name deepstack -e VISION-FACE=True -p 80:5000 deepquestai/deepstack:cpu-2020.12
          cd tests
          export TEST_IMAGES_DIR=$PWD"/images"
          export TEST_DEEPSTACK_URL="http://localhost:80"
          cd face
          python3 -m pytest
          sudo docker container rm -f deepstack
        

  